// All List of Products Constant
export const HOSPITAL_LIST_REQUEST = 'HOSPITAL_LIST_REQUEST';
export const HOSPITAL_LIST_SUCCESS = 'HOSPITAL_LIST_SUCCESS';
export const HOSPITAL_LIST_FAIL = 'HOSPITAL_LIST_FAIL';


// Individual HOSPITAL Delete : Admin Only
export const HOSPITAL_DELETE_REQUEST = 'HOSPITAL_DELETE_REQUEST';
export const HOSPITAL_DELETE_SUCCESS = 'HOSPITAL_DELETE_SUCCESS';
export const HOSPITAL_DELETE_FAIL = 'HOSPITAL_DELETE_FAIL';


export const HOSPITAL_CREATE_REQUEST = 'HOSPITAL_CREATE_REQUEST';
export const HOSPITAL_CREATE_SUCCESS = 'HOSPITAL_CREATE_SUCCESS';
export const HOSPITAL_CREATE_FAIL = 'HOSPITAL_CREATE_FAIL';


export const HOSPITAL_UPDATE_REQUEST = 'HOSPITAL_UPDATE_REQUEST';
export const HOSPITAL_UPDATE_SUCCESS = 'HOSPITAL_UPDATE_SUCCESS';
export const HOSPITAL_UPDATE_FAIL = 'HOSPITAL_UPDATE_FAIL';
export const HOSPITAL_UPDATE_RESET = 'HOSPITAL_UPDATE_RESET';