// All List of OXYGEN Constant
export const OXYGEN_LIST_REQUEST = 'OXYGEN_LIST_REQUEST';
export const OXYGEN_LIST_SUCCESS = 'OXYGEN_LIST_SUCCESS';
export const OXYGEN_LIST_FAIL = 'OXYGEN_LIST_FAIL';


// Individual OXYGEN Delete : Admin Only
export const OXYGEN_DELETE_REQUEST = 'OXYGEN_DELETE_REQUEST';
export const OXYGEN_DELETE_SUCCESS = 'OXYGEN_DELETE_SUCCESS';
export const OXYGEN_DELETE_FAIL = 'OXYGEN_DELETE_FAIL';


export const OXYGEN_CREATE_REQUEST = 'OXYGEN_CREATE_REQUEST';
export const OXYGEN_CREATE_SUCCESS = 'OXYGEN_CREATE_SUCCESS';
export const OXYGEN_CREATE_FAIL = 'OXYGEN_CREATE_FAIL';
export const OXYGEN_CREATE_RESET = 'OXYGEN_CREATE_RESET';



export const OXYGEN_UPDATE_REQUEST = 'OXYGEN_UPDATE_REQUEST';
export const OXYGEN_UPDATE_SUCCESS = 'OXYGEN_UPDATE_SUCCESS';
export const OXYGEN_UPDATE_FAIL = 'OXYGEN_UPDATE_FAIL';
export const OXYGEN_UPDATE_RESET = 'OXYGEN_UPDATE_RESET';